### ISSUE TITLE
How to block until a sequence is complete?

### ISSUE THREAD

**Issue by mikeage** [keatontaylor/alexa_media_player#209]
I'm trying to write an HA script that calls multiple `media_content_type: "sequence"` sequences, but it should wait until the first finishes playback before beginning the second. Otherwise, the second begins immediately, cutting off the first. However, I haven't been able to find any information about making the playback synchronous. Is this possible?

**Comment by alandtse** [comment]
No, we don't have a way to do blocking sequences yet. 

This is primarily a HA issue since everything is async so if you have more than one service call (even with delays), there's no guarantee it will block before the next one is sent to Amazon.  We've had requests to deal with multiple commands like volume changes before TTS #147 . The API may need to be extended to create batched sequences.

**Comment by mikeage** [comment]
Thank you!
