### ISSUE TITLE
Does not work if "Two factor authentication" is enabled on Amazon.com

### ISSUE THREAD

**Issue by ocalvo** [keatontaylor/alexa_media_player#228]
**Describe the bug**
If two factor authentication is enabled on the amazon account, it will loop trying to get a new Capcha challenge and fails to autheticate.

**To Reproduce**
1. Enable TFA on your amazon account
2. Setup the integration

**Expected behavior**
Authetication is performed

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Additional context**

**Comment by alandtse** [comment]
Please turn on [debugging](https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) and carefully review the username, password and captcha being sent to Amazon. What you are describing happens if there is an error with the username, password, or captcha.

Please also ensure you are filling out the configurator prompt in the HA notifications.

**Comment by ocalvo** [comment]
I did the captcha multiple times, and it failed every single time until I deactivated TFA in my amazon account.
Unfortunately, I already setup the component, it works great :)
At this point, I left the decision to close this issue to you. If you have tested the component with an amazon account that has TFA then maybe I was just very unlucky (tried the challenge 3 times)

**Comment by alandtse** [comment]
Glad you got it working. Yes we've tested it with a couple of regions using 2fa. It's how I connect. It's always possible that we're missing a special case so that's why I'd need the logs but I can wait till someone else reports it.
