### ISSUE TITLE
Alexa Guard stays enabled

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#233]
Just FYI guys, started using the API calls to arm/disarm the guard mode and after one day, the white/blue spinning guard mode light is stuck on my five dots. Even if I turn off Alexa Guard via voice, and reboot the Echo dots the light stays on. I've disabled Guard completely, rebooted the Dots, forgot all devices from alexa.amazon.com, etc, etc -- hard rebooted dots -- all in various iterations. Still spinning blue/white light.

_Originally posted by @walthowd in https://github.com/keatontaylor/alexa_media_player/issues/186#issuecomment-506572944_

**Comment by alandtse** [comment]
@walthowd I'm not sure there's much we can do with you but I can see if perhaps something we can help with.  

Can you go to this [url](https://alexa.amazon.com/api/phoenix) and see if there is more than one applianceId with `AAA_OnGuardSmartHomeBridgeService`? 

We look for those entries figure out if there is an AlexaGuard to control. I'm guessing perhaps something happened to spawn more than one instance and that's the one that is stuck on. 

If there are multiple entires, I'll probably need to get the relevant json data to figure it out. You might need to DM me in the HA community forum with a gist of the log so I can look.  Posting here you'd have to remove any serial numbers, etc.


One question may be did you try to rename the Alexa Guard entity or do anything beyond arming and disarming? Someone reported an issue with renaming in #230

**Comment by walthowd** [comment]
Thanks for the suggestions. This is most likely more of a Amazon related bug then related to this component, but I wanted to share just in case it started affecting anyone else. 

I only have one applianceId with AAA_OnGuardSmartHomeBridgeService visible via the phoenix API. I sent you the complete output via the HA forums. 

I also have a call into Amazon support (surprisingly nice and super helpful over the phone), so we will see if anything develops there. 

I didn't rename or change the HA entity in anyway -- I had also seen that issue reported.

Only two other things come to mind:

1) I've had Guard turned on for several weeks now and I have been using TTS via Google homes to turn it on. I upgraded the alexa_media_player component at the same time I upgraded to HA 0.95. To play with the new Alexa entity exposure feature in HA, I used the alexa.amazon.com website to forget all smart home entities. This had the effect of removing the redrock panel entity from Alexa and disabled Guard. I had to turn it back on today.

2) I've been using the **alarm_disarm** service call instead of **alarm_arm_home** service call as that seemed more semantically correct to me. 

Finally, there are a few reports on reddit of the same issue. The resolution there was to completely remove the Alexa devices from the Amazon account and then factory reset the device and rejoin it to the account. I may try that tomorrow.

**Comment by alandtse** [comment]
Thanks for the detail. I'm reviewing the output now, but since it's only the one, my first theory doesn't seem to apply.  

I just wanted to address your point about alarm_disarm vs alarm_arm_home.  It's the same underlying API call. I just left both functions in since: 
1. They're in the default HA component.  
2. Alexa actually uses an API call `ARM_STAY` for the disarm which further made me think Alexa may decide to implement additional functionality for that in the future that is similar to a home setting.

You may want to link the reddit thread in here in case anyone else runs into this problem.

**Comment by walthowd** [comment]
Similar reports of this issue on reddit:

https://www.reddit.com/r/amazonecho/comments/bp5wbu/echo_guard_disabled_spinning_ring_wont_turn_off/

https://www.reddit.com/r/amazonecho/comments/btnadl/echo_dot_has_white_rotating_ring_constantly_how/

**Comment by alandtse** [comment]
Leaving this open for now so others who run into this can report. Otherwise, I don't think it's something we can fix.

**Comment by walthowd** [comment]
FWIW, I unregistered five of my Echo dots and the whole process was pretty painless.

1. Use the Alexa app and unregister each device from your account. 
2. Wait on the dots until the light is spinning blue.
3. Hold down Mute and Volume Down until the device factory resets and the light is spinning orange.
4. Use the Alexa app to re-register the device to your account. 
5. Name the device the same name it had before. 

After that process, there weren't any side effects or extra devices or duplicated media players, etc using this component or others.
