### ISSUE TITLE
sensor.last_alexa goes empty if alexa is triggered on the phone app

### ISSUE THREAD

**Issue by tiagofreire-pt** [keatontaylor/alexa_media_player#249]
**Describe the bug**
sensor.last_alexa returns empty if alexa is triggered on its android app. Returning to the my echo dot, states correctly if triggered there.

**System details**
 - Home-assistant (version): 0.95, with last version of alexa_media_player on HACS.

**Comment by alandtse** [comment]
What do you think the correct behavior should be? Should we ignore the Alexa app and not update the sensor?  The actual devices are not really the last_called device at that point.

**Comment by tiagofreire-pt** [comment]
@alantse, I believe the correct behaviour should be the one I recall from not a while ago, as all devices synchronized with Alexa on Amazon would be detected and used like a Dot3 or Show5, e.g., including the phone App.

The current behaviour is not the one I observe since started to use this custom component. 

Maybe something had broke, on last versions?

**Comment by alandtse** [comment]
We haven't changed the behavior of the `last_called` attribute. What should happen is every device will check whether it is the last_called echo whenever a command is triggered. If that device is, it will set it's attribute to true otherwise it will set itself to false.  

We don't actually provide a `sensor.last_alexa` so I believe you have a template that is checking all the last_called attributes and populating it with the device that reports true.  In theory, even the phone app should report `last_called` accurately, but I actually don't include that entity in my configuration so haven't checked it.

**Comment by tiagofreire-pt** [comment]
This is weird then.

I have two entities regarding this component:

media_player.tiago_s_echo_dot = avaliable and working, as stated on sensor.last_alexa
media_player.tiago_s_alexa_apps = constantly unavailable on home assistant, this is the one that should be showing on sensor.last_alexa when triggering Alexa through the phone app.

**Comment by alandtse** [comment]
The unavailable flag is coming from the fact the API is reporting the app as offline. It's totally possible that that's the default reporting state for the app; I think that's why I stopped including them in my config.

We don't update devices if they are reported as offline. I'll take a look to see if we can easily skip that gate for apps.  However, I think the issue is we can't issue any commands to the Alexa App so the last_echo sensor wouldn't typically be used by most people since they use that sensor to direct a TTS.  Do you have a use case I'm not thinking of?

**Comment by tiagofreire-pt** [comment]
I use the Alexa app as my mobile echo dot. Because it's possible to integrate Alexa on android devices as a personal assistant, instead of the default Google assistant.

The usages are typically the ones for lists, routines and triggering the latters with emulated_hue lights for switching or giving information back through TTS on the app as well on my echo dot 3, depending on which device is triggered. I can trigger lights emulated on HA with emulated_hue on my app, but recently it stopped working the TTS so I don't get any feedback from HA on TTS messages that are encoded in the yaml automations, similarly as the one explained on your wiki here (for emulated_hue integration with this component).

The symptom above is associated with the fact the sensor.last_alexa gets an empty value on a trigger from the app and the entity for the app is unavailable, leading to non receiving TTS messages on the yaml automations (exclusively on the app, as on my echo dot 3 it works flawlessly).

**Comment by alandtse** [comment]
Ok thanks. I understand. I hadn't realized TTS could be directed to the mobile app. It's a bug.

**Comment by alandtse** [comment]
You said this was working before but stopped right? Did you install a new Alexa app on a different phone with the same account or linked account? 

I think the issue is the Alexa can connect multiple phones to the same App instance.  Since, we typically treat each media device as only having 1 serial number, we don't have logic if they have secondary serial numbers.

It also looks like the mobile app is split into multiple `accountNames` depending on the function (play music or TTS).

<details>

```json
{"accountName":"This Device",
"appDeviceList":
[{"deviceAccountId":"devAccount1","deviceType":"A2TF17PFR55MTB","serialNumber":"serNo1"},
{"deviceAccountId":"devAccount2","deviceType":"A2TF17PFR55MTB","serialNumber":"serNo2"}],
"capabilities":["VOLUME_SETTING","DIALOG_INTERFACE_VERSION","MICROPHONE","REMINDERS","ASCENDING_ALARM_VOLUME"],"charging":null,"clusterMembers":[],"deviceAccountId":"devAccount1","deviceFamily":"VOX","deviceOwnerCustomerId":"REDACTED","deviceType":"A2TF17PFR55MTB","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,
"serialNumber":"serNo2","softwareVersion":"130050002"},


{"accountName":"Alan's Alexa Apps",
"appDeviceList":
[{"deviceAccountId":"devAccount3","deviceType":"A1DL2DVDQVK3Q","serialNumber":"serNo3"},
{"deviceAccountId":"devAccount4","deviceType":"A1DL2DVDQVK3Q","serialNumber":"serNo4"}],
"capabilities":["VOLUME_SETTING","MICROPHONE","PEONY"],"charging":null,"clusterMembers":[],"deviceAccountId":"devAccount3","deviceFamily":"AMAZONMOBILEMUSIC_ANDROID","deviceOwnerCustomerId":"REDACTED","deviceType":"A1DL2DVDQVK3Q","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":false,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,
"serialNumber":"serNo4","softwareVersion":"0"}
```

</details>

**Comment by alandtse** [comment]
@tiagofreire-pt any chance you can test the fix I just posted to see if that works for you?  This only fixes the last_called issue. I'll need to spin off another issue for the media player display issue.

**Comment by tiagofreire-pt** [comment]
@alandtse, no, I didn't reinstall the app. Most probably, updated it automatically.

Patched both files as requested and there is an improvement. The sensor.last_alexa does not gets empty if alexa is triggered on the phone but, now, that sensor reports "media_player.this_device" instead the "media_player.tiago_s_alexa_apps" as usual. And no TTS is returned to the phone, still.

**Comment by alandtse** [comment]
Did your phone app use to report on your `alexa_apps` entity?  It's reporting on `This Device` for me.  Can you look up the serial number for your Alexa app for your phone:

1. Go to amazon.com (choose region) in a web browser and login.
2. Hover over Accounts & Lists and click Manage Your Content and Devices.
3. Click to open the Your Devices tab.
4. To the left of each device is a ... button which should pop up the serial number.

After you get the serial number, please check your [devices page (fix region)](https://alexa.amazon.com/api/devices-v2/device) and let me know where the serial number falls under the appDeviceList (whether `This Device`, `Alexa Apps`, or even both).

As for the media player,  #254 will cover the unavailable media player problem. That may be something we can't solve easily because of the way Amazon attaches all apps to `This Device` or `Alexa Apps`. I'm trying to brainstorm if there's an efficient way (but that is in the other thread).

**Comment by tiagofreire-pt** [comment]
Yes, the entity for the phone was automatically created since the begin of using this component.

"69dc0e5f112240b7900baf40b490836e" = "This Device" (Type: Alexa Mobile, under https://www.amazon.com/hz/mycd/myx#/home/devices/1)
"c3a3622732d946808c37b21dc6076669" = "Tiago's Alexa Apps"

I created a new routine to send an "alexa says" and "alexa annoucement", on "alexa will respond from" all options tested sequencially, and triggering Alexa on the phone app, no TTS was noticed on the phone.

**Comment by alandtse** [comment]
From the devices page there is also a `serialNumber` field. Is that the same as the app serial number you found above? Is it a listed app in the `appDeviceList` that you can use still? You may consider deregistering it from Amazon.

By default all of the HA commands use the main `serialNumber`. If it refers to an App you don't have installed anymore, we wouldn't be able to send anything to that. I also suspect Amazon's routines may have the same problem.

**Comment by tiagofreire-pt** [comment]
> 
> 
> From the devices page there is also a `serialNumber` field. Is that the same as the app serial number you found above? Is it a listed app in the `appDeviceList` that you can use still? You may consider deregistering it from Amazon.

The serial numbers on Amazon devices list are above. Could you explain me better your doubt, please?

>
> 
> By default all of the HA commands use the main `serialNumber`. If it refers to an App you don't have installed anymore, we wouldn't be able to send anything to that. I also suspect Amazon's routines may have the same problem.

What do you suggest? Removing this components and do a fresh install?

**Comment by alandtse** [comment]
I was suggesting if you had any old apps registered with Amazon that you deregister then, particularly if they are being listed as the main `serialNumber` instead of the alternates in `appDeviceList`. This could resolve the TTS issues for you as soon as the main `serialNumber` points to the app that is your main one (e.g., `69dc0e...`).

**Comment by tiagofreire-pt** [comment]
I just deleted everything on Amazon device list, but the "Alexa Mobile" and the Dot 3. Now, I receive finally the TTS, when triggering alexa on the phone.

But the TTS is reported to the phone through the "media_player.this_device" not "media_player.tiago_s_echo_dot".

The funny thing is the "media_player.tiago_s_echo_dot" entity is now available, with the status of "standby", but the "media_player.this_device" only stays online and available when there is some triggering of returning the TTS message to the phone. Otherwise is offline and unavailable.

**Comment by alandtse** [comment]
That's the expected behavior for an app. When you have it open it will come online. As soon as you close it, it reports itself as offline. We'll get this fix in the next build. Thanks for your help testing.

**Comment by tiagofreire-pt** [comment]
Thanks @alandtse.

Could you also check if it's possible to reduce the lag between the trigger and the entity to became online? There are at least 6 seconds of it, including the return of TTS. :/

**Comment by alandtse** [comment]
Just to close this out, I don't think we can control the lag as that is basically your mobile phone communicating with Amazon servers and servers communicating to HA.

**Comment by tiagofreire-pt** [comment]
Thanks anyway, @alandtse. Awesome job on this!
